# Generated by Django 3.0.3 on 2020-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cep', models.IntegerField()),
                ('rua', models.CharField(max_length=400)),
                ('complemento', models.CharField(max_length=400)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=10)),
            ],
        ),
    ]
